markdown: rdiscount
permalink: /:title/
url: alcaid1801.github.io
name: 一蓑烟雨任平生
author: 龙山飞俊
qq: 180181340
email: alcaid1801@gmail.com
duoshuo: alcaid
weibo: 1650620703 
github: alcaid1801
pygments: true
safe: true
paginate: 20
